### PR TITLE
Fix CLA GitHub Action after GH org rename

### PR DESCRIPTION
**Pull request by pellared**
https://github.com/cla-assistant/github-action has been migrated to https://github.com/contributor-assistant organization.

### CODE REVIEW

**Review by pjanotti — CHANGES_REQUESTED** [review]
The change itself looks fine, but, we still have some internal Qs to close before merging this.

**Review by Kielek — APPROVED** [review]

**Comment by pellared** [comment]
I think it is safer to update than leaving as it is as someone could occupy the new org name.

**Comment by pjanotti** [comment]
> I think it is safer to update than leaving as it is as someone could occupy the new org name.

That is not as easy as you may think: I heard stories of people trying to get user and org names that they claimed were not used for years and that is not easy.

**Review by pjanotti — APPROVED** [review]
Internal Qs were answered.

**Pull request merged**
